# Generated by Django 3.1.6 on 2022-06-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20220607_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(default='group_image.jpg', upload_to='group_images'),
        ),
    ]
