# Generated by Django 3.1.6 on 2022-06-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20220608_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ['-timestamp']},
        ),
    ]
