# Generated by Django 4.0.4 on 2022-05-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notice_driverslicense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverslicense',
            name='license_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
