# Generated by Django 4.0.4 on 2022-05-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_driverslicense_license_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverslicense',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('declined', 'declined'), ('expired', 'expired')], max_length=10),
        ),
    ]
