# Generated by Django 4.0.4 on 2022-05-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_driverslicense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverslicense',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='driverslicense',
            name='dob',
            field=models.DateField(default='2000-10-1'),
            preserve_default=False,
        ),
    ]
