# Generated by Django 4.0.4 on 2022-05-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_driverslicense_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='dob',
            field=models.DateField(default='1900-10-1'),
        ),
    ]
