# Generated by Django 4.0.4 on 2022-05-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customuser_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='next_of_kin',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
