# Generated by Django 4.0.4 on 2022-05-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_next_of_kin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverslicense',
            old_name='_class',
            new_name='assigned_class',
        ),
    ]
