# Generated by Django 4.0.4 on 2022-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_platenumber_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platenumber',
            name='issues_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
