# Generated by Django 4.0.4 on 2022-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_platenumber_issues_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_image.jpg', upload_to='user_images'),
        ),
    ]
