# Generated by Django 4.0.4 on 2022-05-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
