# Generated by Django 4.0.4 on 2022-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customuser_next_of_kin'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverslicense',
            name='image',
            field=models.ImageField(blank=True, default='license_images.jpg', upload_to='license_images'),
        ),
    ]
