# Generated by Django 4.0.4 on 2022-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_driverslicense_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverslicense',
            name='image',
            field=models.ImageField(blank=True, default='license_images.jpg', upload_to='media/license_images'),
        ),
    ]
